name: ğŸ¤–CI run Regression in QAğŸ§ª
run-name: ${{github.actor}}ğŸ‘¨ğŸ»â€ğŸ”¬ run Regression in ${{github.ref_name}}

on:
  push:
    branches:
      - QA

jobs:
  RegressionTest:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ’»Checkout
        uses: actions/checkout@v3

      - name: ğŸ’¿Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.5'

      - name: ğŸ§¬Install all DevDependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ğŸ§ªSelenium Run Pytest REGRESSION
        run: pytest --headless=true
