name: ğŸ¤–CI run SanityTest ExecutionğŸ§ª
run-name: ${{github.actor}}ğŸ‘¨ğŸ»â€ğŸ”¬ ran SanityTest in ${{github.ref_name}}

on:
  push:
    branches-ignore:
      - QA
      - main

jobs:
  SanityTest:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ’»Checkout
        uses: actions/checkout@v3

      - name: ğŸ’¿Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.5'

      - name: ğŸ§¬Install all DevDependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ğŸ§ªSelenium Run Pytest
        run: pytest --headless=true tests/coverage/example/test_example.py
